package com.centit.support.database.utils;

/**
 * 严格 SQL 注入的稳定诊断码。
 */
public enum StrictSqlReasonCode {
    READY,
    SQL_MISSING,
    FILTERS_MISSING,
    FILTER_ID_DUPLICATED,
    FILTER_NOT_APPLICABLE,
    FILTER_INVALID,
    FILTER_PARTIALLY_COMPILED,
    REQUIRED_ANCHOR_MISSING,
    REQUIRED_ANCHOR_UNCOVERED,
    ANCHOR_INVALID,
    TABLE_REFERENCE_DUPLICATED,
    PARAMETER_COLLISION,
    MALFORMED_TEMPLATE
}
